### ISSUE TITLE
About Distortion Correction

### ISSUE THREAD

**Issue by Easonyesheng** [ori-drs/oxford_spires_dataset#16]
Thanks for this excellent work!
I wonder if there is a way to correct the camera image from a fisheye camera model to a pinhole camera model, like some specific functions in OpenCV or COLMAP.
Looking forward to your reply.

**Comment by YifuTao** [comment]
Thank you for your interest!

There are many ways to rectify the fisheye image to a pinhole camera model.

1. Use [OpenCV fisheye library:](https://docs.opencv.org/4.x/db/d58/group__calib3d__fisheye.html) you will need to first estimate the new camera matrix of the rectified image with 
`cv::fisheye::estimateNewCameraMatrixForUndistortRectify`, and use the estimated intrinsics and distortion parameters to rectify using `cv2.fisheye.initUndistortRectifyMap`, and then finally `cv2.remap`. An [example](https://github.com/leggedrobotics/raw_image_pipeline/blob/556c315a256061ef11bf52a0a74a87736cffe905/raw_image_pipeline/src/raw_image_pipeline/modules/undistortion.cpp#L197-L245) can be found in the raw-image-pipeline we used to white-balance the debayered image.

2. COLMAP can undistort the image in the [`image_undistorter`](https://github.com/ori-drs/oxford_spires_dataset/blob/main/scripts/reconstruction_benchmark/sfm.py#L121). This is used for OpenMVS and Splatfacto in the reconstruction benchmark script. Note that it uses the estimated camera matrix in the SfM process, which can be different from the calibration obtained with Kalibr (see the [sensor config](https://github.com/ori-drs/oxford_spires_dataset/blob/main/config/sensor.yaml), and also check out the calibration folder in the Google Drive).

We might add a script to generate the rectified images to the repository.

**Comment by Easonyesheng** [comment]
Thank you so much for sharing this valuable information!
I'm excited about the possibility of a script being added to the repository for generating rectified images. That would be a great addition to streamline the process.
