### ISSUE TITLE
Need helps for raw image's white balance

### ISSUE THREAD

**Issue by jianhengLiu** [ori-drs/oxford_spires_dataset#19]
Thanks for sharing these excellent datasets! can't wait to try them out!

I noticed that the raw images in the rosbag appear unbalanced, while the images in the "processed" folder have corrected white balance.

Could you please let me know if there is any tool available for this?

Thanks again!

**Comment by YifuTao** [comment]
Hi Jianheng,

Thank you for the message! 

The images in the rosbags are debayered images, without white-balancing. The compressed `images.zip` contains images that are also white-balanced. All of these are processed with [raw_image_pipeline](https://github.com/leggedrobotics/raw_image_pipeline/). The reason to keep the un-white-balanced images in the rosbag is that you can tune / apply your own white-balancing methods to the debayered image. 

### White-balance jpg images
Here is one example using the python binding of the raw image pipeline.
```python
from PIL import Image
import py_raw_image_pipeline

# load the yaml from raw image pipeline. You can manually set it yourself too.
calib_file = "<path-to-raw_image_pipeline>/config/alphasense_calib_1.6mp_example.yaml"
color_calib_file = "<path-to-raw_image_pipeline>/config/alphasense_color_calib_example.yaml"
param_file = "<path-to-raw_image_pipeline>/config/pipeline_params_example.yaml"

image_proc = py_raw_image_pipeline.RawImagePipeline(False, param_file, calib_file, color_calib_file)
image_proc.set_white_balance(True)
image_proc.set_color_calibration(False) # Use auto white balancing instead of a fixed colour calibration matrix
image_proc.set_white_balance_temporal_consistency(True) # If the first few images are well lit, then this helps to correctly white-balance dark rooms afterwards.
image_proc.set_vignetting_correction(True) # apply vignetting correction

input_image = Image.open("<path_to_image>.jpg")
white_balanbed_image = pipeline.process(input_image, debayer_encoding)
```
### White-balance rosbag messages
You can run the raw image pipeline ros node following [their instruction](https://github.com/leggedrobotics/raw_image_pipeline/tree/master?tab=readme-ov-file#run-the-node).

**Comment by jianhengLiu** [comment]
> Hi Jianheng,
> 
> Thank you for the message!
> 
> The images in the rosbags are debayered images, without white-balancing. The compressed `images.zip` contains images that are also white-balanced. All of these are processed with [raw_image_pipeline](https://github.com/leggedrobotics/raw_image_pipeline/). The reason to keep the un-white-balanced images in the rosbag is that you can tune / apply your own white-balancing methods to the debayered image.
> 
> ### White-balance jpg images
> Here is one example using the python binding of the raw image pipeline.
> 
> ```python
> from PIL import Image
> import py_raw_image_pipeline
> 
> # load the yaml from raw image pipeline. You can manually set it yourself too.
> calib_file = "<path-to-raw_image_pipeline>/config/alphasense_calib_1.6mp_example.yaml"
> color_calib_file = "<path-to-raw_image_pipeline>/config/alphasense_color_calib_example.yaml"
> param_file = "<path-to-raw_image_pipeline>/config/pipeline_params_example.yaml"
> use_gpu=False
> 
> image_proc = py_raw_image_pipeline.RawImagePipeline(use_gpu, param_file, calib_file, color_calib_file)
> image_proc.set_white_balance(True)
> image_proc.set_color_calibration(False) # Use auto white balancing instead of a fixed colour calibration matrix
> image_proc.set_white_balance_temporal_consistency(True) # If the first few images are well lit, then this helps to correctly white-balance dark rooms afterwards.
> image_proc.set_vignetting_correction(True) # apply vignetting correction
> 
> input_image = Image.open("<path_to_image>.jpg") # load a debayered image
> debayer_encoding="bgr8"
> white_balanbed_image = image_proc.process(input_image, debayer_encoding)
> ```
> 
> ### White-balance rosbag messages
> You can run the raw image pipeline ros node following [their instruction](https://github.com/leggedrobotics/raw_image_pipeline/tree/master?tab=readme-ov-file#run-the-node).

Thanks a lot, it is easy to get started!
One more thing, I would like to know is where to obtain the intrinsic parameters of the rectified images in "images.zip"

**Comment by YifuTao** [comment]
>One more thing, I would like to know is where to obtain the intrinsic parameters of the rectified images in "images.zip"
You can find the intrinsics from the calibration folder in the Google Drive. I have also added them in this [config in the repo](https://github.com/ori-drs/oxford_spires_dataset/blob/main/config/sensor.yaml) with a sensor class. 

Note that white-balancing doesn't require calibration.

**Comment by jianhengLiu** [comment]
> > One more thing, I would like to know is where to obtain the intrinsic parameters of the rectified images in "images.zip"
> 
> You can find the intrinsics from the calibration folder in the Google Drive. I have also added them in this [config in the repo](https://github.com/ori-drs/oxford_spires_dataset/blob/main/config/sensor.yaml) with a [sensor class](https://github.com/ori-drs/oxford_spires_dataset/blob/main/oxford_spires_utils/sensor.py#L65).
> 
> Note that white-balancing doesn't require calibration. Also images in `images.zip` are not rectified.

Thanks again!
